# Generated by Django 5.0.6 on 2024-07-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='requires_delievery',
            new_name='requires_delivery',
        ),
    ]
